CREATE DATABASE PRIMER_API_CLIENTE

USE PRIMER_API_CLIENTE

CREATE TABLE TB_CLIENTES
(
	CODIGO_CLIENTE		INT NOT NULL PRIMARY KEY,
	NOMBRE_CLIENTE		VARCHAR (50),
	APELLIDO_CLIENTE	VARCHAR(50),
	TELEFONO_CLIENTE	VARCHAR (20),
	CORREO_CLIENTE		VARCHAR (50)
)

--SP LISTAR CLIENTE
CREATE PROCEDURE SP_LISTAR_CLIENTE
AS 
BEGIN
	 SELECT CODIGO_CLIENTE, NOMBRE_CLIENTE,APELLIDO_CLIENTE,TELEFONO_CLIENTE,CORREO_CLIENTE
	 FROM TB_CLIENTES
	 ORDER BY APELLIDO_CLIENTE
END

--SP INSERTAR CLIENTE
ALTER PROCEDURE SP_INSERTAR_CLIENTE
@NOMBRES   VARCHAR (50),
@APELLIDOS VARCHAR (50),
@TELEFONO  VARCHAR (50),
@CORREO     VARCHAR (50)
AS
BEGIN
 BEGIN TRY 
   BEGIN TRANSACTION 
		 DECLARE @CODIGO INT
		 SELECT @CODIGO = ISNULL(MAX(CODIGO_CLIENTE), 0) + 1 FROM TB_CLIENTES
		 INSERT INTO TB_CLIENTES (CODIGO_CLIENTE, NOMBRE_CLIENTE,APELLIDO_CLIENTE,TELEFONO_CLIENTE,CORREO_CLIENTE)
		 VALUES (@CODIGO, @NOMBRES, @APELLIDOS, @TELEFONO, @CORREO)
		 SELECT 1
	COMMIT 
  END TRY 
   BEGIN CATCH 
     ROLLBACK 
	 SELECT 0
   END CATCH
END 

--SP ACTULIZAR CLIENTE
CREATE PROCEDURE SP_ACTUALIZAR_CLIENTE
@NOMBRES   VARCHAR (50),
@APELLIDOS VARCHAR (50),
@TELEFONO  VARCHAR (50),
@CORREO    VARCHAR (50),
@CODIGO	   INT
AS
BEGIN
 BEGIN TRY 
   BEGIN TRANSACTION 
     UPDATE TB_CLIENTES
	  SET NOMBRE_CLIENTE = @NOMBRES,
	      APELLIDO_CLIENTE = @APELLIDOS,
		  TELEFONO_CLIENTE = @TELEFONO,
		  CORREO_CLIENTE  = @CORREO
	  WHERE CODIGO_CLIENTE = @CODIGO
	  SELECT 1
	  COMMIT
 END TRY
    BEGIN CATCH 
     ROLLBACK 
	 SELECT 0
   END CATCH
END

--SP ELIMINAR CLIENTE
CREATE PROCEDURE SP_ELIMINAR_CLIENTE
@CODIGO	   INT
AS
BEGIN
 BEGIN TRY 
   BEGIN TRANSACTION 
    DELETE FROM TB_CLIENTES
	WHERE CODIGO_CLIENTE = @CODIGO
	COMMIT 
	SELECT 1
 END TRY 
     BEGIN CATCH 
     ROLLBACK 
	 SELECT 0
   END CATCH
END